- css/equipo.css
- equipo.html
cartas para información de equipo + css
> cartas para información de equipo + css

- css/proyectos.css
- css/style-general.css
- equipo.html
- index.html
- proyectos.html
arreglos al menú hamburguesa para que se vea bonito
> menu hamburguesa

- proyectos.html
agregando clases al footer en proyectos.html
> agregando clases al footer en proyectos.html

- css/proyectos-detalle.css
arreglos a proyectos-detalle.css
> arreglos a proyectos-detalle.css

- ES/proyectos-detalle/proyectos-detalle-ArmoredCore.html
- ES/proyectos-detalle/proyectos-detalle-Bloodborne.html
- ES/proyectos-detalle/proyectos-detalle-Deracine.html
- ES/proyectos-detalle/proyectos-detalle-MetalWolf.html
- ES/proyectos-detalle/proyectos-detalle-Monhan-Nikki.html
- ES/proyectos-detalle/proyectos-detalle-Sekiro.html
- css/proyectos-detalle.css
agregadas paginas de detalle proyecto ya con informacion
> agregadas paginas de detalle proyecto ya con informacion

- ES/contacto.html
- ES/equipo.html
- ES/noticias.html
agregando script a (contacto, noticias y equipo).html
> agregando script a (contacto, noticias y equipo).html

- EN/contact.html
- EN/index.html
- EN/news.html
- EN/project-detail/project-detail-MetalWolf.html
- EN/projects.html
- EN/team.html
- ES/contacto.html
- ES/equipo.html
- ES/index.html
- ES/noticias.html
- ES/proyectos-detalle/proyectos-detalle-ArmoredCore.html
- ES/proyectos-detalle/proyectos-detalle-Bloodborne.html
- ES/proyectos-detalle/proyectos-detalle-Century.html
- ES/proyectos-detalle/proyectos-detalle-DarkSouls.html
- ES/proyectos-detalle/proyectos-detalle-Deracine.html
- ES/proyectos-detalle/proyectos-detalle-Jutekki.html
- ES/proyectos-detalle/proyectos-detalle-MetalWolf.html
- ES/proyectos-detalle/proyectos-detalle-Monhan-Nikki.html
- ES/proyectos-detalle/proyectos-detalle-Sekiro.html
- ES/proyectos-detalle/proyectos-detalle-Tenchuu.html
- ES/proyectos-detalle/proyectos-detalle-Unicorn.html
- ES/proyectos-detalle/proyectos-detalle-shinshengumi.html
- ES/proyectos.html
- css/style-general.css
Agregado cambio de idioma a header
> Agregado cambio de idioma a header

- css/contacto.css
modificaciones estéticas al formulario
> modificaciones esteticas al formulario

- ES/proyectos-detalle/proyectos-detalle-ArmoredCore.html
- ES/proyectos-detalle/proyectos-detalle-Bloodborne.html
- ES/proyectos-detalle/proyectos-detalle-Century.html
- ES/proyectos-detalle/proyectos-detalle-Deracine.html
- ES/proyectos-detalle/proyectos-detalle-MetalWolf.html
- ES/proyectos-detalle/proyectos-detalle-Monhan-Nikki.html
- ES/proyectos-detalle/proyectos-detalle-Sekiro.html
- ES/proyectos-detalle/proyectos-detalle-Tenchuu.html
- ES/proyectos-detalle/proyectos-detalle-Unicorn.html
- ES/proyectos-detalle/proyectos-detalle-shinshengumi.html
proyectos detalles español finalizado
> proyectos detalle español terminados

- ES/proyectos-detalle/proyectos-detalle-Century.html
- ES/proyectos-detalle/proyectos-detalle-Jutekki.html
- ES/proyectos-detalle/proyectos-detalle-shinshengumi.html
fotos proyecto detalle español corregidas
> fotos proyecto detalle corregido

- EN/projects-detail/projects-detail-ArmoredCore.html
- EN/projects-detail/projects-detail-Bloodborne.html
- EN/projects-detail/projects-detail-Century.html
- EN/projects-detail/projects-detail-DarkSouls.html
- EN/projects-detail/projects-detail-Deracine.html
- EN/projects-detail/projects-detail-Jutekki.html
- EN/projects-detail/projects-detail-MetalWolf.html
- EN/projects-detail/projects-detail-Monhan-Nikki.html
- EN/projects-detail/projects-detail-Sekiro.html
- EN/projects-detail/projects-detail-Tenchuu.html
- EN/projects-detail/projects-detail-Unicorn.html
- EN/projects-detail/projects-detail-shinshengumi.html
corrección de un .html y titulos ingles
> corrección de un .html y titulos

- EN/team.html
> teams.html

- ES/contacto.html
- ES/noticias.html
- ES/proyectos-detalle/proyectos-detalle-ArmoredCore.html
- ES/proyectos-detalle/proyectos-detalle-Bloodborne.html
- ES/proyectos-detalle/proyectos-detalle-Century.html
- ES/proyectos-detalle/proyectos-detalle-DarkSouls.html
- ES/proyectos-detalle/proyectos-detalle-Deracine.html
- ES/proyectos-detalle/proyectos-detalle-Jutekki.html
- ES/proyectos-detalle/proyectos-detalle-MetalWolf.html
- ES/proyectos-detalle/proyectos-detalle-Monhan-Nikki.html
- ES/proyectos-detalle/proyectos-detalle-Sekiro.html
- ES/proyectos-detalle/proyectos-detalle-Tenchuu.html
- ES/proyectos-detalle/proyectos-detalle-Unicorn.html
- ES/proyectos-detalle/proyectos-detalle-shinshengumi.html
actualización de todos los header -index.html
> actualización de todos los header -index.html

- EN/projects-detail/projects-detail-ArmoredCore.html
- EN/projects-detail/projects-detail-Bloodborne.html
- EN/projects-detail/projects-detail-Century.html
- EN/projects-detail/projects-detail-DarkSouls.html
- EN/projects-detail/projects-detail-Deracine.html
- EN/projects-detail/projects-detail-Jutekki.html
- EN/projects-detail/projects-detail-MetalWolf.html
- EN/projects-detail/projects-detail-Monhan-Nikki.html
- EN/projects-detail/projects-detail-Sekiro.html
- EN/projects-detail/projects-detail-Tenchuu.html
- EN/projects-detail/projects-detail-Unicorn.html
- EN/projects-detail/projects-detail-shinshengumi.html
proyectos detalle ingles acabado
> proyectos detalle ingles acabado

- EN/projects.html
- ES/proyectos.html
- css/contacto.css
- css/equipo.css
- css/noticias.css
- css/proyectos.css
- css/style-general.css
titulo en proyectos, projects y correciones en *.css
> titulo en proyectos, projects y correciones en *.css

- EN/projects.html
- ES/proyectos.html
- css/proyectos.css
h2 > h3 proyectos.html y projects.html
> h2 > h3 proyectos.html y projects.html

- EN/news.html
- ES/noticias.html
news.html y noticias.html h2 corregido
> corregido h2 news.html y noticias.html

- css/noticias.css
correcciones esteticas noticias.css
> correcciones esteticas noticias.css

- css/noticias.css
> corrección footer noticias

- ES/proyectos-detalle/proyectos-detalle-Bloodborne.html
- ES/proyectos-detalle/proyectos-detalle-Deracine.html
- ES/proyectos-detalle/proyectos-detalle-MetalWolf.html
- ES/proyectos-detalle/proyectos-detalle-Monhan-Nikki.html
- ES/proyectos-detalle/proyectos-detalle-Sekiro.html
link proyectos detalle español corregidos
> link corregidos

- EN/contact.html
> Formato > Format

- css/contacto.css
- css/equipo.css
- css/index.css
- css/noticias.css
- css/proyectos-detalle.css
- css/proyectos.css
fondo gradiente y opaco el pacman
> fondo gradiente y opaco el pacman

- css/contacto.css
> clase para inputs

- EN/contact.html
mapa pagina contacto ingles añadido
> mapa pagina contacto ingles añadido

- ES/contacto.html
> mapa contacto español añadido

- EN/contact.html
- ES/contacto.html
> mapa contactos añadido

- css/contacto.css
> ajuste tamaño mapa

- EN/contact.html
- css/index.css
- css/proyectos-detalle.css
> tamaño letra index y detalles

- EN/contact.html
- EN/projects-detail/projects-detail-ArmoredCore.html
- EN/projects-detail/projects-detail-Bloodborne.html
- EN/projects-detail/projects-detail-Century.html
- EN/projects-detail/projects-detail-DarkSouls.html
- EN/projects-detail/projects-detail-Deracine.html
- EN/projects-detail/projects-detail-Jutekki.html
- EN/projects-detail/projects-detail-MetalWolf.html
- EN/projects-detail/projects-detail-Monhan-Nikki.html
- EN/projects-detail/projects-detail-Sekiro.html
- EN/projects-detail/projects-detail-Tenchuu.html
- EN/projects-detail/projects-detail-Unicorn.html
- EN/projects-detail/projects-detail-shinshengumi.html
favicon proyecto detalle ingles
> favicon proyecto detalle ingles

- ES/proyectos-detalle/proyectos-detalle-MetalWolf.html
> Año metal wolf

- pokemon/pokemon.html
> footer y header html pokemon

- sudoku/sudoku.css
> error en transición

- sudoku/sudoku.html
> Id de cada cuadricula

- sudoku/app.js
- sudoku/sudoku.css
- sudoku/sudoku.html
> animaciones chulas

- sudoku/app.js
- sudoku/cronometro.js
- sudoku/sudoku.html
- sudoku/sudoku.js
cronometro añadido a la cuadricula
> cronometro añadido

- sudoku/sudoku.css
- sudoku/sudoku.html
añadido div score y posicionado
> añadido div score y posicionado

- pokemon/pokeApp.js
- pokemon/pokeFetch.js
- pokemon/pokemon.css
- pokemon/usuario.js
se crea objeto usuario y se oculta div seleccion
> se crea objeto usuario y se oculta div seleccion

- sudoku/casillas.js
> esCorrecto método
